### ISSUE TITLE
Add default smiley and emoji styles

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/mythic#50]
In version 5.0 of Hybrid Core, we no longer provide stylesheets.  Therefore, we're missing the default styles for smileys and emojis.

Here's a look at the core styles that HC removes.  We need to provide these (minus all the `!important` bits) in `/resources/scss/utilities`.

```css
img.wp-smiley,
img.emoji {
    display: inline !important;
    border: none !important;
    box-shadow: none !important;
    height: 1em !important;
    width: 1em !important;
    margin: 0 .07em !important;
    vertical-align: -0.1em !important;
    background: none !important;
    padding: 0 !important;
}
```
